'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var GET_REQUEST_PL = exports.GET_REQUEST_PL = 'GET_REQUEST_PL';
var PUT_REQUEST_PL = exports.PUT_REQUEST_PL = 'PUT_REQUEST_PL';
var DELETE_REQUEST_PL = exports.DELETE_REQUEST_PL = 'DELETE_REQUEST_PL';
var POST_REQUEST_PL = exports.POST_REQUEST_PL = 'POST_REQUEST_PL';
var RECEIVE_API_DATA = exports.RECEIVE_API_DATA = 'RECEIVE_API_DATA';
var GET_REQUEST_PL_FAILED = exports.GET_REQUEST_PL_FAILED = 'GET_REQUEST_PL_FAILED';
var DELETE_REQUEST_PL_FAILED = exports.DELETE_REQUEST_PL_FAILED = 'DELETE_REQUEST_PL_FAILED';

var SET_ACTIVE_PAGE = exports.SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';

var CHANGE_DATA = exports.CHANGE_DATA = 'CHANGE_DATA';

// export const DELETE_REQUEST_PL = 'DELETE_REQUEST_PL';
// export const DELETE_REQUEST_PL = 'DELETE_REQUEST_PL';