export const GET_REQUEST_PL = 'GET_REQUEST_PL';
export const PUT_REQUEST_PL = 'PUT_REQUEST_PL';
export const DELETE_REQUEST_PL = 'DELETE_REQUEST_PL';
export const POST_REQUEST_PL = 'POST_REQUEST_PL';
export const RECEIVE_API_DATA = 'RECEIVE_API_DATA';
export const GET_REQUEST_PL_FAILED = 'GET_REQUEST_PL_FAILED';
export const DELETE_REQUEST_PL_FAILED = 'DELETE_REQUEST_PL_FAILED';

export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';

export const CHANGE_DATA = 'CHANGE_DATA';

// export const DELETE_REQUEST_PL = 'DELETE_REQUEST_PL';
// export const DELETE_REQUEST_PL = 'DELETE_REQUEST_PL';
